[project]
authors = ["saviorand"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly", "https://repo.prefix.dev/mojo-community-nightly", "https://repo.prefix.dev/mojo-community"]
description = "Author APIs in Pure Mojo"
name = "lightbug_api"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
test = { cmd = "magic run mojo test -I . tests" }
format = { cmd = "magic run mojo format -l 120 lightbug_api" }

[dependencies]
max = ">=24.5.0,<25"
lightbug_http = "0.1.4.dev2024092905"
